### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by AndreasBrostrom** [7Cav/SandboxAndTrainingMissionGenerator#1]
* Define globals via ini file instead of header.
   - [x] Set author
   - [x] Island array
   - [x] Spawn array
   - [x] Set author
   - [x] Island array
   - [x] Define mission framework zip
   - [x] Change CBA settings

* Functions
   - [x] Add functionality to set spawn position of a starter crate.
